version: "2"
services:
  app:
    build: ./app
    command: python manage.py run -h 0.0.0.0
    links:
      - db
    ports:
      - "5000:5000"
      
    depends_on:
      - db

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: